export const USER_ROLES = {
  PATIENT: 'user',
  COUNSELOR: 'counselor',
  DOCTOR: 'doctor',
  HOSPITAL_ADMIN: 'hospital_admin',
  BRANCH_ADMIN: 'branch_admin',
  NURSE_LAB_TECHNICIAN: 'nurse_lab_technician',
  PHARMACIST: 'pharmacist',
  RECEPTIONIST: 'receptionist',
  BILLING_ACCOUNTS: 'billing_accounts',
  HOUSEKEEPING: 'housekeeping',
  SUPER_ADMIN: 'super_admin',
};

export const ROLE_ALIASES = {
  patient: USER_ROLES.PATIENT,
  user: USER_ROLES.PATIENT,
  counsellor: USER_ROLES.COUNSELOR,
  counselor: USER_ROLES.COUNSELOR,
  psychologist: USER_ROLES.COUNSELOR,
  doctor: USER_ROLES.DOCTOR,
  specialist: USER_ROLES.DOCTOR,
  hospital_admin: USER_ROLES.HOSPITAL_ADMIN,
  hospitaladmin: USER_ROLES.HOSPITAL_ADMIN,
  branch_admin: USER_ROLES.BRANCH_ADMIN,
  branchadmin: USER_ROLES.BRANCH_ADMIN,
  nurse: USER_ROLES.NURSE_LAB_TECHNICIAN,
  lab: USER_ROLES.NURSE_LAB_TECHNICIAN,
  lab_technician: USER_ROLES.NURSE_LAB_TECHNICIAN,
  nurse_lab_technician: USER_ROLES.NURSE_LAB_TECHNICIAN,
  pharmacist: USER_ROLES.PHARMACIST,
  receptionist: USER_ROLES.RECEPTIONIST,
  billing: USER_ROLES.BILLING_ACCOUNTS,
  accounts: USER_ROLES.BILLING_ACCOUNTS,
  billing_accounts: USER_ROLES.BILLING_ACCOUNTS,
  housekeeping: USER_ROLES.HOUSEKEEPING,
  super_admin: USER_ROLES.SUPER_ADMIN,
  superadmin: USER_ROLES.SUPER_ADMIN,
};

